export enum Token {
    UNKNOWN = 'unknown',
    PWRD = 'pwrd',
    GVT = 'gvt',
    GRO = 'gro',
    DAI = 'dai',
    USDC = 'usdc',
    USDT = 'usdt',
    TUSD = 'tusd',
    FRAX = 'frax',
    OUSD = 'ousd',
    ALUSD = 'alusd',
    LUSD = 'lusd',
    GUSD = 'gusd',
    WETH = 'weth',
    AVAX = 'avax',
    BALANCER_GRO_WETH = 'balancer_gro_weth',
    UNISWAP_GVT_GRO = 'uniswap_gvt_gro',
    UNISWAP_GRO_USDC = 'uniswap_gro_usdc',
    CURVE_PWRD3CRV = 'curve_pwrd3crv',
    THREE_CRV = '3crv'
}
